"""The CI no-skip gate is executed here, not read.

``.github/workflows/ci.yml`` carries an inline Python script -- the "No test was skipped" step --
whose whole job is to fail the build when the suite quietly stops running tests. It shipped with a
defect that made it unable to do that: ``suites`` was the lazy generator returned by
``Element.iter()``, the skip scan consumed it, and the ``sum`` that followed therefore added up an
exhausted generator. Every green run printed ``0 tests ran, none skipped`` -- including a local run
of 2775 tests.

The wrong number was the harmless half. A total pinned to zero cannot distinguish a full suite from
a collection that produced nothing, which is precisely the failure the step exists to catch, so the
reassuring line was reporting something it was not measuring.

The existing workflow tests in ``tests/test_url_ingest.py`` assert that strings appear in this file.
That would not have caught this: every string was already correct. So this module extracts the
script and **runs** it against reports built to order, in keeping with the working agreement --
anything that parses another program's output gets a test that runs against real output rather than
a description of it. The XML here is pytest's own JUnit report, generated by pytest.
"""

from __future__ import annotations

import re
import subprocess
import sys
import textwrap
import xml.etree.ElementTree as ET

import pytest

from config import BASE_DIR

#: Matches the heredoc body of the "No test was skipped" step. Anchored on the step name so it
#: cannot drift onto one of the other inline scripts in the file (the vendored-fonts check and the
#: coverage step are both `python - <<'PY'` too).
_GATE = re.compile(r"No test was skipped.*?python - <<'PY'\n(.*?)\n          PY\n", re.S)


@pytest.fixture(scope="module")
def gate_source() -> str:
    """The gate's Python, lifted out of the workflow and de-indented."""
    workflow = (BASE_DIR / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    match = _GATE.search(workflow)
    assert match, "could not find the 'No test was skipped' script in .github/workflows/ci.yml"
    return textwrap.dedent(match.group(1))


def _run(gate_source: str, tmp_path, report: bytes | None) -> subprocess.CompletedProcess[str]:
    """Run the gate in ``tmp_path`` against ``report``, or against no report at all."""
    script = tmp_path / "gate.py"
    script.write_text(gate_source, encoding="utf-8")
    if report is not None:
        (tmp_path / "pytest-report.xml").write_bytes(report)
    return subprocess.run(
        [sys.executable, "gate.py"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )


def _report(*, tests: int, skipped: int = 0, flaky: int = 0) -> bytes:
    """A JUnit report shaped like pytest's: one ``testsuite`` under a ``testsuites`` root."""
    root = ET.Element("testsuites", {"name": "pytest tests"})
    suite = ET.SubElement(
        root,
        "testsuite",
        {
            "name": "pytest",
            "errors": "0",
            "failures": "0",
            "skipped": str(skipped),
            "tests": str(tests),
        },
    )
    for index in range(tests):
        case = ET.SubElement(
            suite, "testcase", {"classname": "tests.test_thing", "name": f"test_{index}"}
        )
        if index < skipped:
            ET.SubElement(case, "skipped", {"message": "ffmpeg not found", "type": "pytest.skip"})
        elif index < skipped + flaky:
            ET.SubElement(case, "flaky", {"message": "rerun"})
    return ET.tostring(root)


def test_a_clean_report_passes_and_reports_the_real_count(gate_source, tmp_path):
    """The regression. This asserts the *resolved* count, not merely that the gate exited 0.

    Under the generator bug the exit status was still 0 and the words "none skipped" still
    appeared, so any assertion weaker than the number itself passed against the broken gate.
    """
    result = _run(gate_source, tmp_path, _report(tests=2775))

    assert result.returncode == 0, result.stderr
    assert "2775 tests ran, none skipped." in result.stdout
    assert "0 tests ran" not in result.stdout


def test_one_skipped_test_fails_the_build_and_names_it(gate_source, tmp_path):
    """A skip is not a pass, and the message has to say which test and why."""
    result = _run(gate_source, tmp_path, _report(tests=10, skipped=1))

    assert result.returncode == 1
    assert "A skipped test is not a passing test" in result.stdout
    assert "tests.test_thing::test_0" in result.stdout
    assert "ffmpeg not found" in result.stdout


def test_a_flaky_rerun_also_fails(gate_source, tmp_path):
    """``flaky`` is checked alongside ``skipped``: a test that had to be rerun is not asserting."""
    result = _run(gate_source, tmp_path, _report(tests=10, flaky=1))

    assert result.returncode == 1
    assert "flaky: tests.test_thing::test_0" in result.stdout


def test_a_report_with_no_tests_fails(gate_source, tmp_path):
    """The hole the generator bug left open.

    A report carrying zero tests is a collection failure. With the total hard-wired to 0 this case
    printed the same line as a clean 2775-test run and passed.
    """
    result = _run(gate_source, tmp_path, _report(tests=0))

    assert result.returncode == 1
    assert "zero tests" in result.stderr


def test_a_missing_report_fails(gate_source, tmp_path):
    """The step runs under ``always()``, so it is reached when pytest itself never got going."""
    result = _run(gate_source, tmp_path, None)

    assert result.returncode == 1
    assert "the suite did not run" in result.stderr


def test_the_gate_handles_a_bare_testsuite_root(gate_source, tmp_path):
    """The `else [root]` branch: some pytest versions emit `testsuite` as the document element."""
    suite = ET.Element(
        "testsuite",
        {"name": "pytest", "errors": "0", "failures": "0", "skipped": "0", "tests": "3"},
    )
    for index in range(3):
        ET.SubElement(suite, "testcase", {"classname": "tests.test_thing", "name": f"t{index}"})

    result = _run(gate_source, tmp_path, ET.tostring(suite))

    assert result.returncode == 0, result.stderr
    assert "3 tests ran, none skipped." in result.stdout
